version: '3'

services:
  monitoring_container:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    restart: always

  python_container:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always